FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY database.py .
COPY drain_analysis.py .
COPY drain3.ini .
COPY log_parser.py .
COPY raw_log_reader.py .
COPY main.py .

# Expose port
EXPOSE ${API_PORT:-8000}

# Run FastAPI with uvicorn

CMD uvicorn main:app \
    --host 0.0.0.0 \
    --port ${API_PORT:-8000} \
    --workers ${API_WORKERS:-1}